### ISSUE TITLE
Can't build with Carthage using Xcode 8, Carthage 0.18.1

### ISSUE THREAD

**Issue by erikackermann** [ipfs/swift-ipfs-api#3]
Have the following Cartfile:

```
github "ipfs/swift-ipfs-api"
```

And am running `carthage update --platform iOS` and it fails on the step to compile SwiftBase58:

```
The following build commands failed:
	CompileSwift normal arm64 /Users/erik/devenv/swift-ipfs-api/Carthage/Checkouts/SwiftBase58/SwiftBase58/SwiftBase58.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal armv7 /Users/erik/devenv/swift-ipfs-api/Carthage/Checkouts/SwiftBase58/SwiftBase58/SwiftBase58.swift
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/Headers/SwiftBase58-Swift.h /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58-Swift.h
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/Headers/SwiftBase58-Swift.h /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58-Swift.h
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm.swiftmodule /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58.swiftmodule
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm.swiftdoc /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58.swiftdoc
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm64.swiftmodule /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58.swiftmodule
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm64.swiftdoc /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58.swiftdoc
	Ld /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58 normal armv7
	Ld /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58 normal arm64
	CreateUniversalBinary /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/SwiftBase58 normal armv7\ arm64
	GenerateDSYMFile /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework.dSYM /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/SwiftBase58
(14 failures)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/erik/devenv/swift-ipfs-api/Carthage/Checkouts/SwiftBase58/SwiftBase58.xcodeproj -scheme SwiftBase58 -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/erik/devenv/swift-ipfs-api/Carthage/Checkouts/SwiftBase58/SwiftBase58/SwiftBase58.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal armv7 /Users/erik/devenv/swift-ipfs-api/Carthage/Checkouts/SwiftBase58/SwiftBase58/SwiftBase58.swift
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/Headers/SwiftBase58-Swift.h /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58-Swift.h
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/Headers/SwiftBase58-Swift.h /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58-Swift.h
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm.swiftmodule /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58.swiftmodule
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm.swiftdoc /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58.swiftdoc
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm64.swiftmodule /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58.swiftmodule
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm64.swiftdoc /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58.swiftdoc
	Ld /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58 normal armv7
	Ld /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58 normal arm64
	CreateUniversalBinary /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/SwiftBase58 normal armv7\ arm64
	GenerateDSYMFile /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework.dSYM /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-hjiaqhpgpkxgkqfoszoaxzxrkczg/Build/Products/Release-iphoneos/SwiftBase58.framework/SwiftBase58
(14 failures)
```

The Xcode build log contains a bunch of errors like this:

```
swift-ipfs-api/Carthage/Checkouts/SwiftBase58/SwiftBase58/SwiftBase58.swift:76:19: error: use of unresolved identifier 'IntBig'
```

**Comment by NeoTeo** [comment]
I have just tested it on Xcode 8 (8A218a) and Carthage 0.18.1 and it builds without problems. 
This suggests there may be some problem with your environment. Make sure you remove your Carthage directory and the Cartfile.resolved file and that your xcodebuild version matches your Xcode.

**Comment by erikackermann** [comment]
Are able to build with Carthage on macOS 10.12 Sierra?

I'm using Xcode 8 (verified that it's build 8A218a), Carthage 0.18.1 and macOS 10.12.

In a directory with just a single text file `Cartfile` containing:

```
github "ipfs/swift-ipfs-api"
```

I'm running `carthage update --platform iOS` and I get the following:

```
*** Fetching swift-ipfs-api
*** Fetching SwiftMultiaddr
*** Fetching SwiftMultihash
*** Fetching VarInt
*** Fetching SwiftBase58
*** Fetching SwiftHex
*** Fetching SwiftHex
*** Fetching SwiftGMP
*** Checking out SwiftGMP at "d2c7b0eed3fb1fc8f31c18027696901971223fee"
*** Checking out SwiftHex at "173baac156e3bb40c987a74f9f2550204a6fc939"
*** Checking out SwiftBase58 at "85116ca9d52d0f52da1a8b95fe36b724a6fcca53"
*** Checking out SwiftMultihash at "7082d60aed2a30d63c33e313760d6947533a061f"
*** Checking out VarInt at "b5abebc1b2567885000cb1fee534bf67aadc6a64"
*** Checking out SwiftMultiaddr at "93d29b31f32f8a8bda25e84d2938407edd1faa6d"
*** Checking out swift-ipfs-api at "v0.2"
*** xcodebuild output can be found in /var/folders/2h/7c31v2t13vx7p9hf8dsrtd4c0000gn/T/carthage-xcodebuild.3nwtw8.log
*** Building scheme "SwiftGMP" in SwiftGMP.xcodeproj
*** Building scheme "SwiftHex" in SwiftHex.xcodeproj
*** Building scheme "SwiftBase58" in SwiftBase58.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/erik/swift-ipfs-api/Carthage/Checkouts/SwiftBase58/SwiftBase58/SwiftBase58.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal armv7 /Users/erik/swift-ipfs-api/Carthage/Checkouts/SwiftBase58/SwiftBase58/SwiftBase58.swift
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/Headers/SwiftBase58-Swift.h /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58-Swift.h
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/Headers/SwiftBase58-Swift.h /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58-Swift.h
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm.swiftmodule /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58.swiftmodule
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm.swiftdoc /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58.swiftdoc
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm64.swiftmodule /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58.swiftmodule
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm64.swiftdoc /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58.swiftdoc
	Ld /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58 normal armv7
	Ld /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58 normal arm64
	CreateUniversalBinary /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/SwiftBase58 normal armv7\ arm64
	GenerateDSYMFile /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework.dSYM /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/SwiftBase58
(14 failures)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/erik/swift-ipfs-api/Carthage/Checkouts/SwiftBase58/SwiftBase58.xcodeproj -scheme SwiftBase58 -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/erik/swift-ipfs-api/Carthage/Checkouts/SwiftBase58/SwiftBase58/SwiftBase58.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal armv7 /Users/erik/swift-ipfs-api/Carthage/Checkouts/SwiftBase58/SwiftBase58/SwiftBase58.swift
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/Headers/SwiftBase58-Swift.h /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58-Swift.h
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/Headers/SwiftBase58-Swift.h /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58-Swift.h
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm.swiftmodule /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58.swiftmodule
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm.swiftdoc /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58.swiftdoc
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm64.swiftmodule /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58.swiftmodule
	Ditto /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/Modules/SwiftBase58.swiftmodule/arm64.swiftdoc /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58.swiftdoc
	Ld /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/armv7/SwiftBase58 normal armv7
	Ld /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Intermediates/SwiftBase58.build/Release-iphoneos/SwiftBase58.build/Objects-normal/arm64/SwiftBase58 normal arm64
	CreateUniversalBinary /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/SwiftBase58 normal armv7\ arm64
	GenerateDSYMFile /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework.dSYM /Users/erik/Library/Developer/Xcode/DerivedData/SwiftBase58-cijswhvrmgzhzfegvcmmgifgntoo/Build/Products/Release-iphoneos/SwiftBase58.framework/SwiftBase58
(14 failures)
```

I'm new to Carthage, maybe I'm using the tool incorrectly?  Any help with this would be appreciated.

**Comment by NeoTeo** [comment]
What branch are you using? The versions that are being checked out are not correct. Your Checking out lines should read: 
```
*** Fetching SwiftMultiaddr
*** Fetching SwiftMultihash
*** Fetching VarInt
*** Fetching SwiftBase58
*** Fetching SwiftGMP
*** Fetching SwiftHex
*** Checking out SwiftGMP at "e7f90f5612291e1bcb2e2bd175fd0c9ddd84a0d4"
*** Checking out SwiftHex at "v0.3"
*** Checking out SwiftBase58 at "5d8196e6ea68ddffa59060bb66d984f0e151553f"
*** Checking out SwiftMultihash at "40f05fc881541b8ac12f8d8c62f92d414dcb30f1"
*** Checking out VarInt at "b5abebc1b2567885000cb1fee534bf67aadc6a64"
*** Checking out SwiftMultiaddr at "b7f0c57496aedb5933be06159b59a8d55f1df27f"
*** xcodebuild output can be found in /var/folders/qx/gcnhmzf529gdkndv2wbz57n00000gn/T/carthage-xcodebuild.Or5WZl.log
*** Building scheme "SwiftGMP" in SwiftGMP.xcodeproj
*** Building scheme "SwiftHex" in SwiftHex.xcodeproj
*** Building scheme "SwiftBase58" in SwiftBase58.xcodeproj
*** Building scheme "SwiftMultihash" in SwiftMultihash.xcodeproj
*** Building scheme "VarInt" in VarInt.xcodeproj
*** Building scheme "SwiftMultiaddr" in SwiftMultiaddr.xcodeproj
```

**Comment by NeoTeo** [comment]
I think I know what the problem is. Try changing your Cartfile to read:

github "ipfs/swift-ipfs-api" "master"

I think this is due to a recent change in Carthage where, if not specified, it will check out the last tagged version as opposed to the head of the branch.

**Comment by erikackermann** [comment]
Ah yes, that was the issue.  Thank you for your help!
